#define VMA_IMPLEMENTATION
#define VMA_DYNAMIC_VULKAN_FUNCTIONS 1
#define VMA_STATIC_VULKAN_FUNCTIONS 0
#define VMA_EXTERNAL_MEMORY 0
#define VMA_NULLABLE _Nullable
#define VMA_NOT_NULL _Nonnull
#define VMA_VULKAN_VERSION 1002000
#include "vk_mem_alloc.h"